[workspace]
authors = ["nihildigit <nihildigit@outlook.com>"]
channels = ["rapidsai", "conda-forge"]
name = "hw_ml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.9"

[dependencies]
python = "3.11.*"

cuda-version = "12.9.*"

pytorch-gpu = "2.9.*"
torchvision = "0.24.*"

cuml = { version = "25.12.*", channel = "rapidsai" }

numpy = "*"
pandas = "*"
scipy = "*"
scikit-learn = "*"
matplotlib = "*"
scienceplots = "*"
tqdm = "*"
tabulate = ">=0.9.0,<0.10"

