[workspace]
authors = ["nihildigit <nihildigit@outlook.com>"]
channels = ["conda-forge"]
name = "hw_ml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "13.0"

[dependencies]
python = "3.11.*"
pytorch-gpu = "2.9.*"
torchvision = "0.24.*"
numpy = "*"
pandas = "*"
scipy = "*"
scikit-learn = "*"
matplotlib = "*"
scienceplots = "*"
tqdm = "*"
tabulate = ">=0.9.0,<0.10"

